site_name: TronLink Docs
use_directory_urls: false
site_url: http://127.0.0.1:8000/

theme:
  name: material
  logo: images/logo.png
  # custom_dir: docs/overrides
  features:
    - navigation.sections  # 启用左侧导航栏的分组
    - navigation.footer
    - toc.integrate
    - search.highlight  # 搜索时高亮匹配内容
    - search.suggest  # 搜索时显示建议
    - content.code.annotate  # 代码块注释
    - content.tooltips  # 内容中的工具提示
  palette:
    primary: 'blue'  # 主色调
    accent: custom  # 强调色
  font:
    text: Roboto  # 正文字体
    code: Roboto Mono  # 代码字体

markdown_extensions:
    - admonition   # 支持mkdoc的提示框、文本框、代码框等
    - codehilite # 代码高亮
    - toc:
        permalink: true  # 为每个标题添加锚点图标，方便复制链接
        toc_depth: 4    # 	限制目录显示的标题层级，避免目录过长


