site_name: TronLink 开发者文档
site_description: TronLink 钱包开发者文档，包含移动端、插件钱包和 DApp 开发指南
site_author: TronLink Team
site_url: https://docs.tronlink.org/
# 仓库信息
repo_name: tronlink-doc
repo_url: https://github.com/TronLink/docs.git

# 主题配置
theme:
  name: material
  custom_dir: docs/overrides
  language: en
  logo: images/logo.png
  # 功能配置
  features:
    - navigation.sections
    # - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - toc.integrate
    - search.highlight  # 搜索时高亮匹配内容
    - search.suggest  # 搜索时显示建议
    - content.code.annotate  # 代码块注释
    - content.tooltips  # 内容中的工具提示
  # 字体配置
  font:
    text: Roboto  # 正文字体
    code: Roboto Mono  # 代码字体

extra_css:
    - stylesheets/extra.css

extra_javascript:
    - javascripts/toc.js
    - javascripts/nav-toc.js

# 插件配置
plugins:
  - search
  - minify:
      minify_html: true
  - i18n:
      default_language: en
      docs_structure: suffix   
      languages:
        - locale: en
          name: English
          site_name: TronLink Docs
          default: true
          build: true
          nav:
            # - Home: index.en.md
            - Introduction: introduction.en.md
            - HD Wallets: hd-wallets.en.md
            - TronLink App:
              - Asset Management: mobile/asset-management.en.md
              - DeepLink: mobile/deeplink.en.md
              - DApp Support: mobile/dapp-support.en.md
            - TronLink Wallet Extension:
              - Request TronLink Extension: plugin-wallet/active-requests.en.md
              - Receive messages from TronLink: plugin-wallet/passive-messages.en.md
            - DApp:
              - Start Developing: dapp/getting-started.en.md
              - Multi-Signature Transfer: dapp/multi-sign-transfer.en.md
              - Message Signature: dapp/message-signing.en.md
              - General Transfer: dapp/transfer.en.md
              - Stake2.0: dapp/stake2.en.md
        - locale: zh
          name: 中文
          site_name: TronLink 开发者文档
          build: true
          nav:
            - 介绍: introduction.zh.md
            - HD 钱包: hd-wallets.zh.md
            - 移动端:
              - 资产管理: mobile/asset-management.zh.md
              - DeepLink: mobile/deeplink.zh.md
              - DApp支持: mobile/dapp-support.zh.md
            - 插件钱包:
              - 主动请求TronLink插件功能: plugin-wallet/active-requests.zh.md
              - 被动接收TronLink插件的消息: plugin-wallet/passive-messages.zh.md
            - DApp:
              - 开始开发: dapp/getting-started.zh.md
              - 多签转账: dapp/multi-sign-transfer.zh.md
              - 消息签名: dapp/message-signing.zh.md
              - 普通转账: dapp/transfer.zh.md
              - Stake2.0: dapp/stake2.zh.md
      use_directory_urls: true  # 推荐保持为 true     
      suffix_mode: true 

# 版权信息
copyright: Copyright &copy; 2025 TronLink Team

# 验证
validation:
  nav:
    omitted_files: ignore
  not_found: warn 
