#!/usr/bin/env python3
"""Generate docs/llms-full.txt by concatenating the English source docs.

llms-full.txt is the single-fetch, full-text variant of llms.txt
(https://llmstxt.org/). It bundles every English page so an LLM can ingest
the whole documentation set in one request.

Run from the repo root:

    python3 scripts/gen_llms_full.py

Pages are emitted in navigation order (mirroring the `en` nav in mkdocs.yml).
Re-run this whenever docs change; wire it into CI to keep it in sync.
"""
from __future__ import annotations

from pathlib import Path

DOCS = Path(__file__).resolve().parent.parent / "docs"
OUT = DOCS / "llms-full.txt"
SITE = "https://docs.tronlink.org/docs"

# English source pages, in nav order (see mkdocs.yml).
PAGES = [
    "introduction.en.md",
    "hd-wallets.en.md",
    "dapp/getting-started.en.md",
    "ai-support/ai-llms.en.md",
    "mobile/asset-management.en.md",
    "mobile/deeplink.en.md",
    "mobile/dapp-support.en.md",
    "plugin-wallet/active-requests.en.md",
    "plugin-wallet/passive-messages.en.md",
    "plugin-wallet/ledger-signing-update.en.md",
    "ai-support/mcp-server-tronlink.en.md",
    "ai-support/tronlink-mcp-core.en.md",
    "ai-support/tronlink-skills.en.md",
    "ai-support/mcp-tronlink-signer.en.md",
    "ai-support/tronlink-signer.en.md",
    "ai-support/tronlink-cli.en.md",
    "dapp/transfer.en.md",
    "dapp/multi-sign-transfer.en.md",
    "dapp/message-signing.en.md",
    "dapp/stake2.en.md",
    "reference/networks.en.md",
    "reference/glossary.en.md",
    "reference/faq.en.md",
]


def page_url(rel: str) -> str:
    # introduction.en.md -> /introduction/ ; mobile/deeplink.en.md -> /mobile/deeplink/
    slug = rel[: -len(".en.md")]
    return f"{SITE}/{slug}/"


def main() -> None:
    parts: list[str] = [
        "# TronLink Developer Documentation — Full Text",
        "",
        "> Concatenation of all English documentation pages for single-fetch "
        "LLM ingestion. Generated by scripts/gen_llms_full.py. See "
        f"{SITE}/llms.txt for the curated index.",
        "",
    ]
    missing: list[str] = []
    for rel in PAGES:
        path = DOCS / rel
        if not path.exists():
            missing.append(rel)
            continue
        parts.append("---")
        parts.append("")
        parts.append(f"<!-- source: docs/{rel} | url: {page_url(rel)} -->")
        parts.append("")
        parts.append(path.read_text(encoding="utf-8").rstrip())
        parts.append("")
    OUT.write_text("\n".join(parts) + "\n", encoding="utf-8")
    print(f"Wrote {OUT.relative_to(DOCS.parent)} ({len(PAGES) - len(missing)} pages)")
    if missing:
        raise SystemExit("Missing pages: " + ", ".join(missing))


if __name__ == "__main__":
    main()
