#!/usr/bin/env python3
"""Generate docs/llms-full.txt by concatenating the English source docs.

llms-full.txt is the single-fetch, full-text variant of llms.txt
(https://llmstxt.org/). It bundles every English page so an LLM can ingest
the whole documentation set in one request.

Run from the repo root:

    python3 scripts/gen_llms_full.py

Pages are emitted in navigation order (mirroring the `en` nav in mkdocs.yml).
Re-run this whenever docs change; wire it into CI to keep it in sync.
"""
from __future__ import annotations

import subprocess
from datetime import datetime, timezone
from pathlib import Path

DOCS = Path(__file__).resolve().parent.parent / "docs"
REPO = DOCS.parent
OUT = DOCS / "llms-full.txt"


def git_short_sha() -> str:
    """Return short SHA of the worktree HEAD, or 'unknown' if git fails."""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--short=12", "HEAD"],
            cwd=REPO,
            check=True,
            capture_output=True,
            text=True,
        )
        return result.stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"


def estimate_tokens(char_count: int) -> int:
    """Rough token estimate (~4 chars per token, OpenAI heuristic).

    Coarse on purpose: we want an order-of-magnitude hint for agents
    deciding whether to ingest the whole file. Zero-dep by choice.
    """
    return char_count // 4
# In-repo links use root-relative /docs/ paths (no hardcoded domain),
# so they work under any domain (prod, staging, test).

# English source pages, in nav order (see mkdocs.yml).
PAGES = [
    "introduction.en.md",
    "hd-wallets.en.md",
    "dapp/getting-started.en.md",
    "ai-support/ai-llms.en.md",
    "mobile/asset-management.en.md",
    "mobile/deeplink.en.md",
    "mobile/dapp-support.en.md",
    "plugin-wallet/active-requests.en.md",
    "plugin-wallet/passive-messages.en.md",
    "plugin-wallet/ledger-signing-update.en.md",
    "ai-support/mcp-server-tronlink.en.md",
    "ai-support/tronlink-mcp-core.en.md",
    "ai-support/tronlink-skills.en.md",
    "ai-support/mcp-tronlink-signer.en.md",
    "ai-support/tronlink-signer.en.md",
    "ai-support/tronlink-cli.en.md",
    "dapp/transfer.en.md",
    "dapp/multi-sign-transfer.en.md",
    "dapp/message-signing.en.md",
    "dapp/stake2.en.md",
    "reference/networks.en.md",
    "reference/glossary.en.md",
    "reference/faq.en.md",
]


def page_url(rel: str) -> str:
    # introduction.en.md -> /docs/introduction/ ; mobile/deeplink.en.md -> /docs/mobile/deeplink/
    # Root-relative (under the /docs base path), so no domain is hardcoded.
    slug = rel[: -len(".en.md")]
    return f"/docs/{slug}/"


def main() -> None:
    sha = git_short_sha()
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    body_parts: list[str] = []
    missing: list[str] = []
    for rel in PAGES:
        path = DOCS / rel
        if not path.exists():
            missing.append(rel)
            continue
        body_parts.append("---")
        body_parts.append("")
        body_parts.append(f"<!-- source: docs/{rel} | url: {page_url(rel)} -->")
        body_parts.append("")
        body_parts.append(path.read_text(encoding="utf-8").rstrip())
        body_parts.append("")

    body = "\n".join(body_parts)
    token_estimate = estimate_tokens(len(body))

    header = [
        "# TronLink Developer Documentation — Full Text",
        "",
        "> Concatenation of all English documentation pages for single-fetch "
        "LLM ingestion. Generated by scripts/gen_llms_full.py. "
        "See /docs/llms.txt for the curated index.",
        "",
        f"- Generated: {generated_at}",
        f"- Commit: {sha}",
        f"- Pages: {len(PAGES) - len(missing)}",
        f"- Token estimate: ~{token_estimate:,} (chars / 4)",
        "",
    ]

    OUT.write_text("\n".join(header) + body + "\n", encoding="utf-8")
    print(
        f"Wrote {OUT.relative_to(REPO)} "
        f"({len(PAGES) - len(missing)} pages, commit {sha}, ~{token_estimate:,} tokens)"
    )
    if missing:
        raise SystemExit("Missing pages: " + ", ".join(missing))


if __name__ == "__main__":
    main()
